### PR TITLE
fix(headless-ui): fix prefix option not found bug

### LINKED ISSUE #294: vite.config.js中配置HeadlessUiResolver启动报错
image
在Components中添加HeadlessUiResolver会报Cannot read property 'prefix' of undefined，将HeadlessUiResolver注释掉可以正常运行

### PR DESCRIPTION
**Pull request by ycs77**
fix #294

### CODE REVIEW

File: src/core/resolvers/headless-ui.ts [hunk 1]
```diff
@@ -56,12 +56,11 @@ export interface HeadlessUiResolverOptions {
...
  * @link https://github.com/tailwindlabs/headlessui
  */
-export function HeadlessUiResolver({
-  prefix = '',
-}: HeadlessUiResolverOptions): ComponentResolver {
+export function HeadlessUiResolver(options: HeadlessUiResolverOptions = {}): ComponentResolver {
   return {
     type: 'component',
     resolve: (name: string) => {
+      const { prefix = '' } = options
```
Comment (antfu) [inline src/core/resolvers/headless-ui.ts:63]: Should do the destructure in upper function

Comment (ycs77) [reply src/core/resolvers/headless-ui.ts]: OK
